### ISSUE TITLE
contao-dms/bundle-all, error via composer contao 3.4.3-3.4.5

### ISSUE THREAD

**Issue by Soeldner** [ContaoDMS/bundle-all#1]
Fatal error: Class 'tl_dms_documents' not found in /var/www/system/modules/DocumentManagementSystem/dca/tl_dms_documents.php on line 204

test 3 times on fresh systems. 

the error appears during installation. Only a blank page appears without an error message on the tab documents (do = dms_documents).
Composer makes mistakes after installation. Uninstall is possible.

**Comment by cliffparnitzky** [comment]
I assume you installed the highest verion (something with 3....). This was not a correct version (is now deleted). Please try with version 1.1.1

**Comment by Soeldner** [comment]
Sorry for the late reply. Thanks for the note. works great.

**Comment by cliffparnitzky** [comment]
:+1:
